version: '3.8'

name: SolvdDemoblaze

services:
  chrome:
    image: seleniarm/standalone-chromium:latest
    container_name: standalone-chrome
    shm_size: 2gb
    ports:
      - "4444:4444"
  firefox:
    image: seleniarm/standalone-firefox:latest
    container_name: standalone-firefox
    shm_size: 2gb
    ports:
      - "4445:4444"