#===Common===
explicit_timeout=15
auto_screenshot=true
url=https://www.demoblaze.com/index.html

#===Desktop===
browser=chrome
selenium_url=http://localhost:4444/wd/hub
auto_download=false

#===Mobile General===
#driver_type=mobile
#selenium_url=http://127.0.0.1:4723/

#===Android===
#capabilities.platformName=Android
#capabilities.deviceName=Pixel 6 Pro
#capabilities.browserName=Chrome

#===iOS===
#capabilities.platformName=iOS
#capabilities.deviceName=iPhone 17
#capabilities.platformVersion=26.5
#capabilities.browserName=Safari
#capabilities.appium:usePrebuiltWDA=true